version: '3.4'

services:
  diplom:
    image: ${DOCKER_REGISTRY-}diplom
    build:
      context: .
      dockerfile: Diplom/Dockerfile

  animals-api:
    image: ${DOCKER_REGISTRY-}animals-api
    build:
      context: .
      dockerfile: AnimalManagement/Dockerfile


  ads-api:
    image: ${DOCKER_REGISTRY-}ads-api
    build:
      context: .
      dockerfile: Ads/Dockerfile

  ads-data:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1401:1433"

  users-data:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1402:1433"