version: '3.4'

services:
  diplom:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  animals-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  #ads-api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://+:80
  #  ports:
  #    - "80"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  coordinates-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  clientads-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  images-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ads-data:
    environment:
      - SA_PASSWORD=BrRX@6IxL#
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"

  users-data:
    environment:
      - SA_PASSWORD=BrRX@6IxL#
      - ACCEPT_EULA=Y
    ports:
      - "1402:1433"

  animals-data:
    environment:
      - SA_PASSWORD=BrRX@6IxL#
      - ACCEPT_EULA=Y
    ports:
      - "1403:1433"

  coordinates-data:
    environment:
      - SA_PASSWORD=BrRX@6IxL#
      - ACCEPT_EULA=Y
    ports:
      - "1404:1433"

  images-data:
    environment:
      - SA_PASSWORD=BrRX@6IxL#
      - ACCEPT_EULA=Y
    ports:
      - "1405:1433"

  api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
