// <auto-generated />
using System;
using Ads.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ads.Migrations
{
    [DbContext(typeof(AdContext))]
    partial class AdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Model.Ads.Ad", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusAd")
                        .HasColumnType("int");

                    b.Property<int>("TypeAd")
                        .HasColumnType("int");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Model.Ads.AdCoordinates", b =>
                {
                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(36, 18)
                        .HasColumnType("decimal(36,18)");

                    b.HasKey("AdGuid");

                    b.ToTable("AdCoordinates");
                });

            modelBuilder.Entity("Model.Ads.Animals.Animal", b =>
                {
                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnimalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ColorOfAnimalGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsOtherColorOfAnimal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOtherKindOfAnimal")
                        .HasColumnType("bit");

                    b.Property<Guid>("KindOfAnimalGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OtherColorOfAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherKindOfAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexAnimal")
                        .HasColumnType("int");

                    b.HasKey("AdGuid");

                    b.HasIndex("ColorOfAnimalGuid");

                    b.HasIndex("KindOfAnimalGuid");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Model.Ads.Animals.ColorOfAnimal", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("ColorsOfAnimals");
                });

            modelBuilder.Entity("Model.Ads.Animals.KindOfAnimal", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KindName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("KindsOfAnimals");
                });

            modelBuilder.Entity("Model.Ads.Image", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageHash")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Guid");

                    b.HasIndex("AdGuid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Model.Ads.AdCoordinates", b =>
                {
                    b.HasOne("Model.Ads.Ad", "Ad")
                        .WithOne("Coordinates")
                        .HasForeignKey("Model.Ads.AdCoordinates", "AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("Model.Ads.Animals.Animal", b =>
                {
                    b.HasOne("Model.Ads.Ad", "Ad")
                        .WithOne("Animal")
                        .HasForeignKey("Model.Ads.Animals.Animal", "AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Ads.Animals.ColorOfAnimal", null)
                        .WithMany()
                        .HasForeignKey("ColorOfAnimalGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Ads.Animals.KindOfAnimal", null)
                        .WithMany()
                        .HasForeignKey("KindOfAnimalGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("Model.Ads.Image", b =>
                {
                    b.HasOne("Model.Ads.Ad", "Ad")
                        .WithMany("Photo")
                        .HasForeignKey("AdGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("Model.Ads.Ad", b =>
                {
                    b.Navigation("Animal");

                    b.Navigation("Coordinates");

                    b.Navigation("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
